---
apiVersion: v1
kind: Service
metadata:
  name: wilk-service
  namespace: wilk-portfolio
spec:
  selector:
    app: wilk-portfolio-app
  ports:
    - protocol: TCP
      port: 80 # This is for the external port
      targetPort: 80 # This is for the internal port
  type: LoadBalancer
