name: Build and Deploy Vite React Project

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' # Ensures deploy runs only on PR events
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ../projects/portfolio-work
            git checkout main
            git pull
            npm i
            npm run build
            cp -R ./dist/* ../../var/www/html/

      # - name: Deploy to remote server
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #   run: |
      #     # Add the remote server's SSH key to known_hosts to prevent host verification prompts
      #     mkdir -p ~/.ssh
      #     ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          
      #     # Use SCP to copy the build files to the remote server
      #     scp -i ~/.ssh/id_rsa -r dist/* root@${{ secrets.SERVER_IP }}:/var/www/html/

