name: Build and Deploy Vite React Project

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify your Node.js version here

      - name: Install dependencies
        run: npm install

      - name: List files in build directory
        run: ls -la

      - name: Build the project
        run: npm run build # Adjust this if you use a different script

      - name: List files in build directory
        run: ls -la

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist # Adjust if your build output directory is different

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: List files in build directory
        run: ls -la

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' # Ensures deploy runs only on PR events
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: List files in build directory
        run: ls -la

        # - name: Deploy to remote server
        #   run: |
        #     git pull
        #     npm i
        #     npm run build
        #     cp -R ./dist/*
        #     # scp -i ~/.ssh/id_ed25519 -r dist/* root@${{ secrets.SERVER_IP }}:/var/www/html/
        # env:
        #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
